### ISSUE TITLE
Retrieving number with getValueAsync returns boolean

### ISSUE THREAD

**Issue by titivermeesch** [configcat/common-js#104]
### Describe the bug

I'm using the configcat-node wrapper

I have a feature flag containing a numeric value (5 digits). When using `ConfigCatClient#getValueAsync` I receive `true` back instead of the actual value. Even if I delete the feature flag from the admin panel I still receive `true`.

I enabled debug logs and I can see from the logs that it successfully retrieves the numeric value from the API. When I use `getValueDetailsAsync` I also receive the correct value.

### To reproduce

1. Add a numeric setting to the ConfiCat admin panel
2. Query the flag with `getValueAsync`

### Expected behavior

The numeric value should be returned

**Comment by titivermeesch** [comment]
As an extra point, I cannot reproduce this in a sandbox environment but am wondering what could cause this

**Comment by laliconfigcat** [comment]
Hello @titivermeesch ,

I'm sorry to hear that you run into an issue with our SDK. Could you please write an email to support@configcat.com with the affected SDK key and the feature flag's key so we can check what is happening?
Also, please share how do you initialize the SDK and how do you call the getValueAsync function.

Cheers,
Lali
