### ISSUE TITLE
Marking bundle side effect free

### ISSUE THREAD

**Issue by davincho** [configcat/common-js#16]
According to https://bundlephobia.com/result?p=configcat-common@3.0.2, the bundle is tree-shakable but not marked as side effect free.

After having a quick check on the code, the bundle could be marked as side effect free like so: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

Any concerns in doing so?

**Comment by endret** [comment]
> According to https://bundlephobia.com/result?p=configcat-common@3.0.2, the bundle is tree-shakable but not marked as side effect free.
> 
> After having a quick check on the code, the bundle could be marked as side effect free like so: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
> 
> Any concerns in doing so?

Hi @davincho ,
Thank you for the report, we will extend the `package.json` with related `side Effects` property in the next release.
Cheers
