### ISSUE TITLE
e.Equals is not a function

### ISSUE THREAD

**Issue by s5no5t** [configcat/common-js#21]
My team is occasionally seeing end users run into an `e.Equals is not a function` exception:

![grafik](https://user-images.githubusercontent.com/3235163/97186462-990ef580-17a1-11eb-8979-11a207fb7840.png)

Do you have any idea what may be causing this? Is there a workaround?

**Comment by laliconfigcat** [comment]
Hey,

Which SDK version are you using? I'm pretty sure that this issue was fixed in the last version. Could you please update to it?

Cheers,
Lali

**Comment by s5no5t** [comment]
I think we were using common-js 4.2.0 and configcat-js 5.3.0

**Comment by s5no5t** [comment]
We have since then updated to 4.2.1 and not seen the issue. I'll let you know if it comes up again.
