### ISSUE TITLE
Race condition with `client.dispose()`

### ISSUE THREAD

**Issue by eirikurn** [configcat/common-js#36]
### Describe the bug

We have a fast running node script which hangs because of the configcat client, even though we call it's dispose function at the end.

Digging into the issue, we see that the dispose method calls `clearTimeout(this.timerId)`, where `timerId` is undefined. At this time, it's still invoking `refreshLogic` for the first time. After `refreshLogic` finishes, it sets a timeout to refresh again, even after the client has been disposed. This causes the process to hang.

### To reproduce

Run this script with node:

```js
const configcat = require('configcat-node').createClient('<<SDK KEY>>)
configcat.dispose()
```

### Expected behavior

Node process should exit. Instead it hangs.

**Comment by laliconfigcat** [comment]
Hello @eirikurn,

Thanks for reporting the issue. I just started working on improving the auto poll and lazyload modes a bit, I'll take care of this issue. I'll keep you updated.

Cheers,
Lali

**Comment by laliconfigcat** [comment]
This PR will take care of your problem: https://github.com/configcat/common-js/pull/37

**Comment by eirikurn** [comment]
Awesome! Thanks for the super quick reaction time. I look forward to the release. 👍

**Comment by laliconfigcat** [comment]
Hello @eirikurn ,

I just released v6.7.0 from the Node SDK. I hope it will solve your problem.

Cheers,
Lali

**Comment by eirikurn** [comment]
It works great. Thanks for an awesome service and resolution speed!

**Comment by leeran88** [comment]
Hello @laliconfigcat,

We encountered an issue in our production services - after a few days, suddenly the configcat client gets out of sync and 
returns old values when calling `getAllValues`. When it happens, the client will no longer gets the updated values.

We use v6.6.0 of the Node SDK, and instantiate the client as a singleton, like recommended.

Do you think this is the same issue described in #37, and upgrading to v6.7.0 will solve our issue?

Thanks!

**Comment by laliconfigcat** [comment]
Hello @leeran88 ,

Generally, it is always a good idea to keep the SDK updated. Could you please share some more details about what did you experience? Do you have any logs regarding this issue? It would help us a lot in investigating your issue.

Cheers,
Lali

**Comment by leeran88** [comment]
@laliconfigcat Unfortunately the SDK doesn't output any logs in this case. It just returns outdated values.
I can say that it happens when the service is up for a while, after a few days or a week, and seems like it stops fetching the json file at some point after this period of time.. and we use auto polling.

When restarting the service (re-creating the client), it gets the correct values.

From what I read in #37 in the second change (2), it sounds related:

> 2. Fixes the expired cache problem around AutoPolling mode. In auto polling mode if e.g. the local storage cache (JS SDK) is available the client didn't check the maxInitWaitTimeSeconds so the first n calls could return bad, expired values. The fix is checking if the cached config.json's timestamp is older than the (now-auto polling interval) and if it is older, the maxInitWaitTimeSeconds logic should apply too. AutoPollConfigService.tryReadFromCache() modifications.
>
> Test cases:
> * Initialization With AutoPollOptions with expired cache - getValue should take care of maxInitWaitTimeSeconds
> * Initialization With AutoPollOptions with expired cache - getValueAsync should take care of maxInitWaitTimeSeconds

**Comment by laliconfigcat** [comment]
@leeran88 Could you please try updating the SDK to the latest version and check if that solves the problem or not? Also if it doesn't solve it, could you please open another issue for the SDK as this one is closed?

Thanks,

**Comment by leeran88** [comment]
@laliconfigcat sure, will do.
I'll update the SDK and wait for a week or so and update.
Thanks!

**Comment by leeran88** [comment]
@laliconfigcat unfortunately upgrading to 6.7.1 didn't solve the issue.
I opened a new issue for the SDK as requested:
https://github.com/configcat/node-sdk/issues/39
