### ISSUE TITLE
Odd? values in DataGovernance enum

### ISSUE THREAD

**Issue by GabrielCousin** [configcat/common-js#42]
### Describe the bug

Hello, I'm currently working on updating the [Ember addon](https://github.com/MakeMusicInc/ember-config-cat) we published for ConfigCat.
I ran into some TypeScript error: when trying to build a typed options object for the ConfigCat Client, I noticed some difference between the DataGovernance exported here https://github.com/configcat/common-js/blob/df5ef91401aa3cc15139240adfe7d371ce28c2c7/src/ConfigCatClientOptions.ts#L8 and the value expected by the documentation here https://configcat.com/docs/sdk-reference/js#auto-polling-default
Which are the correct values?:
- `0` or `1`
- `Global` or `EuOnly`?

### To reproduce

TypeScript Sandbox https://www.typescriptlang.org/play?#code/PQKhAIGEHsDsBcBO0A254AsCm4XQMYCG8AlnONAGbrbj5yUkDmAdAFYDO5jKWHdceIRKwRTcAE9oAV0ThKWYrJyUUhJv0KwAJuA5Z4pWBvAB3EphE0cMWIyaRiUACIA5FuBDAAUFgAeAA7QiPDgWLDSALbgzsSEAOLQAG5YiLBa+DgA3t7geeCgEADKWLz4oZb8JNRSsvKK8MryaiaEiDgB0gBGKCQc2Lrw0OCEKGhMeF2jLq7gsNDafB5eufnxk9MAvOAADAA0q3mF4CVlFRh94NWSMnIKSu3N6pqPnT19A+jDkG5zC3wUWAoCRXWDWcAAUQAqssfPlIdIAPJAkHbACM3gAvt4cSJ4KlKIRMuBEQFSHB+Dl4do4okUmkMlgAFwxWnJVLpWCZADcWJx9FgHFC0DJZEFOxZpPJgvA2yp+RpQjpHMZLIA5OtoFMUGq+fyKcLRRS0ZKjTK5YdwIqEuyGVzmbssUA

### Expected behavior

From my point of view, I wonder if the enum values should be Global/EuOnly instead

### Screenshots

None

**Comment by z4kn4fein** [comment]
Hi @GabrielCousin 

Thank you for reaching out! The documentation you mentioned expects the enum value not as a string like `'Global'`, but the value accessed like `DataGovernance.Global`. [Here](https://www.typescriptlang.org/play?#code/PQKhAIGEHsDsBcBO0A254AsCm4XQMYCG8AlnONAGbrbj5yUkDmAdAFYDO5jKWHdceIRKwRTcAE9oAV0ThKWYrJyUUhJv0KwAJuA5Z4pWBvAB3EphE0cMWIyaRiUACIA5FuBDAAUFgAeAA7QiPDgWLDSALbgzsSEAOLQAG5YiLBa+DgA3t7geeCgEADKWLz4oZb8JNRSsvKK8MryaiaEiDgB0gBGKCQc2Lrw0OCEKGhMeF2jLq7gsNDafB5eufnxk9MAvOAADAA0q3mF4CVlFRh94NWSMnIKSu3N6pqPnT19A+jDkG5zC3wUWAoCRXWDWcAAUQAqssfPlIdIAPJAkHbACM3gAvt4cSJ4KlKIRMuBEQFSHB+Dl4do4okUmkMlgAFwxWnJVLpWCZADcWJx9FgHFC0DJZEFOxZpPJgvA2yp+RpQjpHMZLNiSvZDK5WBY62gUxQfP5FOFoopaMlZplcsO4EVCU1nMyLJ2WKAA), I updated your sandbox example to demonstrate. We might want to make this clearer in the documentation.

Is there a specific reason you want to use its value as a string?

**Comment by GabrielCousin** [comment]
Thank you for sharing more details.
That makes sense! I don't need to use the value as a string, I assume I haven't understood the documentation as it was meant. Based on your feedback, I will update the addon accordingly and we can close this issue since it's not one :)
Thanks again!

**Comment by z4kn4fein** [comment]
Thank you for sharing this addon with us! It looks exciting :)
Let us know if you have further questions!
