### ISSUE TITLE
With autopoll initial tryReadFromCache takes 5 seconds

### ISSUE THREAD

**Issue by teunmooij** [configcat/common-js#43]
### Describe the bug

We're using a toggle immediately after loading our application and noticed a 5 second delay of our application loading. After debugging the problem I noticed that although the configcat cdn replies within 30ms, the first `client.getValueAsync` still takes almost **5 seconds** (default config value for `maxInitWaitTimeSeconds`).

Our configuration: configcat-js v5.7.2 with AutoPoll:

```typescript
import { createClientWithAutoPoll, createConsoleLogger } from 'configcat-js'
const logger = createConsoleLogger(LogLevel.Off)
const client = createClientWithAutoPoll('our-key', {
    logger,
    pollIntervalSeconds: 300,
    requestTimeoutMs: 5000,
  })

const getValue =  <T>(featureName: string, defaultValue: T, context: any) => client.getValueAsync(featureName, defaultValue, context)
```

### Expected behavior

Since loading the config takes about 25ms and evaluation of most settings about 15ms I would expect a responsetime of approx 40ms.

### Cause of the issue:

- `AutoPollConfigService.tryReadFromCache` checks for timeStamp of the cache (line 85) and will keep waiting for a cache update until `maxInitWaitTimeStamp` has passed;
- `AutoPollConfigService.startRefreshWorker` calls `refreshLogic` with `forceUpdateCache = false` (line 64), therefore `ConfigServiceBase.refreshLogicBaseAsync` will not update the cache if the configuration hasn't changed since the last visit to our website. Since cache is persisted in localstorage it will still have the old timestamp.

### Suggested solution:

Code change in `AutoPollConfigService.ts` to force cache update on startup:

line 20:
```typescript
this.startRefreshWorker(autoPollConfig.pollIntervalSeconds * 1000, true);
```

`startRefreshWorker`:
```typescript
    private startRefreshWorker(delay: number, forceUpdateCache = false) {
        this.refreshLogic(forceUpdateCache).then((_) => {
            if (this.disposed) {
                return;
            }
            this.timerId = setTimeout(
                () => {
                    this.startRefreshWorker(delay);
                },
                delay);
        });
    }
```

**Comment by laliconfigcat** [comment]
Hello @teunmooij ,

Thanks for reporting the issue. We'll check it soon.

Cheers,

**Comment by laliconfigcat** [comment]
Hello @teunmooij ,

We just released a new version of the JS-based SDKs with the fix. I hope it will solve your problem.

Cheers,

**Comment by teunmooij** [comment]
Thanks!
I've seen the PR. I'm pretty sure it will.
