### ISSUE TITLE
BUG - Update to 1.4.0

### ISSUE THREAD

**Issue by townmi** [configcat/common-js#5]
## Current Behavior
```
Uncaught TypeError: ConfigServiceBase_1.ProjectConfig is not a constructor
```
## Possible Solution
```
export ProjectConfig
```
## Detailed Description
https://github.com/configcat/common-js/blob/d261a2cea6b0c3944dee64a7834c6eaf13f04a11/src/ConfigServiceBase.ts#L3

**Comment by configcat** [comment]
Hello,

We moved the ProjectConfig from ConfigServiceBase to an own ProjectConfig.ts file.
We just released a new js-sdk with the new common-js lib, and here you can see how we resolved this issue:
https://github.com/configcat/js-sdk/commit/9fba7ba4518c1aed5ab6bc12bd08c738e957bde2#diff-0786f4512c3c17d1fc8dade614545901

import { ProjectConfig } from "configcat-common/lib/ConfigServiceBase";
->
import { ProjectConfig } from "configcat-common/lib/ProjectConfig";

Cheers,
Lajos from ConfigCat
