### ISSUE TITLE
Allow optional custom fields

### ISSUE THREAD

**Issue by jannnik** [configcat/common-js#8]
We would like to use some optional custom fields in the configcat user. Actually the typings don't allow optional strings as custom fields and we have to use a workaround. 

Please allow undefined as value in the custom object: https://github.com/configcat/common-js/blob/master/src/RolloutEvaluator.ts#L31

`custom?: { [key: string]: string | undefined } = {};`

**Comment by configcat** [comment]
Hi Jannik,

Thank you for your request.

We prefer the strongly typed solutions and that is the reason why we do not support the 'undefined' one. This solution works with null, empty string and in this case the evaluation will be ignored.
Can you tell us an example of a situation where you have to set 'undefined' for custom field? (The sdk doesn't support either the 'undefinied' at id, email or country.)

Cheers,
Andrew

**Comment by configcat** [comment]
23 days have passed without a response, we are closing this issue.
Feel free to reopen it if you are still interested.
